name = "notion-inbox-triage"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
INBOX_DB_ID = "2e2dec27c9aa809d82f0db2ca819140c"
TASKS_DB_ID = "2e1dec27c9aa808a8e8dd8c09955e4a1"


[triggers]
crons = ["0 22 * * *"]
